version: '3'

volumes:
  eccube-data:
  db-data:


services:
  db:
    image: mysql:5.6
    environment:
      - name=value
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cube3_dev
      - MYSQL_USER=cube3_dev_user
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

  eccube:
    build: ./eccube
    environment:
      - DBSERVER=db
      - AUTH_MAGIC=XjosAXOzO1B3mE0egwQA
      - MAIL_HOST=mailcatcher
      - MAIL_PORT=1025
    ports:
      - 80:80
    volumes:
      - eccube-data:/var/data
    depends_on:
      - db

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
